### PR TITLE
Added block diagram to README

### PR DESCRIPTION
**Pull request by marnovandermaas**

### CODE REVIEW

**Comment by hcallahan-lowrisc** [comment]
Is it worth putting the image of the Arty-A7 + mandelbrot at the top of the README too? Would be eye-catching!

**Comment by marnovandermaas** [comment]
Good idea, I've added that as well.

**Comment by hcallahan-lowrisc** [comment]
Looks good! Can go for a lower-res version? 3.5MB is quite a lot for a git repo really...

**Review by ctopal — APPROVED** [review]
Looks great!

**Comment by GregAC** [comment]
SVGs will render in github markdown so no need for the rendered PNG version of the diagram

**Comment by marnovandermaas** [comment]
> Looks good! Can go for a lower-res version? 3.5MB is quite a lot for a git repo really...

Good point, I've added a smaller version of the image.

**Pull request merged**
